apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "medusa.fullname" . }}
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ include "medusa.databaseUrl" . | quote }}
  REDIS_URL: {{ include "medusa.redisUrl" . | quote }}
  ADMIN_CORS: {{ .Values.medusa.adminCors | quote }}
  STORE_CORS: {{ .Values.medusa.storeCors | quote }}
  {{- range $key, $value := .Values.medusa.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}