replicaCount: 1

accessKey: minioadmin
secretKey: minioadmin

persistence:
  enabled: false   # ephemeral for local dev
  size: 10Gi

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: "minio.local"
      paths:
        - path: /
          pathType: Prefix
  tls: []  # optional: add TLS if you want
